### ISSUE TITLE
Issue in profile.php

### ISSUE THREAD

**Issue by Hetachi** [E-REP/E-REP#2]
```
When user attempts to comment himself:
```

Notice: Undefined index: myusername in C:\xampp\htdocs\E-REP\profile.php on line 66

**Comment by Solivar** [comment]
Log in first.

**Comment by Hetachi** [comment]
I was logged in

**Comment by Solivar** [comment]
I don't see any issues when commenting in your own profile.

**Comment by Hetachi** [comment]
http://www.bildites.lv/viewer.php?file=ylmcvat6auy7bcxi2lj.png

**Comment by Solivar** [comment]
Maybe you could finally explain what you do to get this error?

**Comment by Solivar** [comment]
Update your MySQL database next time.
